language: go

go:
  - 1.15.x

jobs:
  include:
    - stage: "Compile"
      name: "Compile Packages and Dependencies"
      script:
        - go mod download
        - go build -v

    - stage: "Tests"
      name: "Unit Tests"
      script: go test -v

    - stage: "Install"
      name: "Install package"
      script: go install -v

    - stage: "Code Quality"
      name: "Code Quality Analysis"
      script: docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:latest golangci-lint run -v