language: go

go:
  - 1.15.x

sudo: required

services:
  - docker

jobs:
  include:
    - stage: "Compile"
      name: "Compile Packages and Dependencies"
      script:
        - go mod download
        - go build -v

    - stage: "Tests"
      name: "Unit Tests"
      script: go test -v

    - stage: "Install"
      name: "Install package"
      script: go install -v

    - stage: "Code Quality"
      name: "Code Quality Analysis"
      script: docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:latest golangci-lint run -v

    - stage: "Docker Quality"
      name: "Docker Quality Analysis"
      script: docker run --rm -i hadolint/hadolint:latest < Dockerfile

    - stage: "Deploy docker"
      if: branch = master AND type = push AND fork = false 
      name: "Deploy docker to docker registry"      
      before_script:
        - docker --version
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      script:
        - docker build -t maksimall89/dozor18_bot:latest .
        - docker push maksimall89/dozor18_bot:latest
        
stages:
  - "Compile"
  - "Tests"
  - "Install"
  - "Code Quality"
  - "Docker Quality"
  - "Compile"
  - "Deploy docker"