package src

import (
	"database/sql"
	"fmt"
	_ "github.com/lib/pq"
	"log"
	"strings"
)

const errConnectPattern = "Unable to connect to database: %v\n"

func (confDataBase *DataBase) DBInsertCodesUsers() {
	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		log.Printf(errConnectPattern, err)
	}
	defer db.Close()

	_, err = db.Exec("INSERT INTO CodesUser (Time, NickName,  Code, Danger, Sector) VALUES ($1, $2, $3, $4, $5)",
		confDataBase.Time, confDataBase.NickName, confDataBase.Code, confDataBase.Danger, confDataBase.Sector)
	if err != nil {
		log.Println(err)
	}
}
func (confDataBase *DataBase) DBInsertCodesRight(addData string) string {
	strArr := strings.Split(addData, ",")
	if len(strArr) < 3 {
		return "Слишком короткая строка: /add Code,Danger,Sector"
	}

	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		return fmt.Sprintf(errConnectPattern, err)
	}
	defer db.Close()

	_, err = db.Exec("INSERT INTO CodesRight (Code, Danger, Sector) VALUES ($1, $2, $3)",
		strings.TrimSpace(strArr[0]), strings.TrimSpace(strArr[1]), strings.TrimSpace(strArr[2]))
	if err != nil {
		return fmt.Sprintf("Unable to INSERT INTO CodesRight: %v\n", err)
	}

	return "&#10004;Данные <b>добавлены</b> в БД."
}
func (confDataBase *DataBase) DBDeleteCodesRight(deleteStr string) string {
	if len(deleteStr) < 2 {
		return "Слишком короткая строка: /delete CodeOld"
	}

	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		return fmt.Sprintf(errConnectPattern, err)
	}
	defer db.Close()

	_, err = db.Exec("DELETE FROM CodesRight WHERE Code = $1", deleteStr)
	if err != nil {
		return fmt.Sprintf("Unable to DELETE CodesRight: %v\n", err)
	}

	return "&#8252;Данные <b>удалены</b> в БД=" + deleteStr
}
func (confDataBase *DataBase) DBUpdateCodesRight(updateData string) string {
	strArr := strings.Split(updateData, ",")
	if len(strArr) < 4 {
		return "Нет всех аргументов: /update CodeNew,Danger,Sector,CodeOld"
	}

	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		return fmt.Sprintf(errConnectPattern, err)
	}
	defer db.Close()

	_, err = db.Exec("UPDATE CodesRight SET Code = $1, Danger = $2, Sector=$3 WHERE Code = $4",
		strings.TrimSpace(strArr[0]), strArr[1], strArr[2], strings.TrimSpace(strArr[3]))
	if err != nil {
		return fmt.Sprintf("Unable to UPDATE CodesRight: %v\n", err)
	}

	return "&#10071;Данные <b>обновлены</b> в БД."
}
func (confDataBase *DataBase) DBSelectCodes() []DataBase {
	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		log.Printf(errConnectPattern, err)
	}
	defer db.Close()

	rows, err := db.Query("SELECT Time, Code FROM CodesUser WHERE NickName = $1", confDataBase.NickName)
	if err != nil {
		log.Println(err)
	}
	defer rows.Close()

	var data []DataBase
	for rows.Next() {
		d := DataBase{}
		err := rows.Scan(&d.Time, &d.Code)
		if err != nil {
			log.Println(err)
			continue
		}
		data = append(data, d)
	}

	return data
}
func (confDataBase *DataBase) DBResetAllCodes() (str string) {
	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		return fmt.Sprintf(errConnectPattern, err)
	}
	defer db.Close()

	// delete table
	_, err = db.Exec("DROP TABLE IF EXISTS CodesUser")
	if err != nil {
		str += fmt.Sprintf("ERROR delete CodeUser: %s", err)
	}
	_, err = db.Exec("DROP TABLE IF EXISTS CodesRight")
	if err != nil {
		str += fmt.Sprintf("ERROR delete CodesRight: %s", err)
	}

	// create table
	_, err = db.Exec("CREATE TABLE " +
		"CodesUser( " +
		"Number integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
		"Time    varchar(40) NOT NULL," +
		"NickName    varchar(100) NOT NULL," +
		"Code    varchar(300) NOT NULL," +
		"Danger   varchar(30) NOT NULL," +
		"Sector   varchar(100) NOT NULL);")
	if err != nil {
		str += fmt.Sprintf("ERROR create CodesUser: %s", err)
	}
	_, err = db.Exec("CREATE TABLE " +
		"CodesRight(" +
		"Number integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
		"Code    varchar(300) NOT NULL," +
		"Danger   varchar(30) NOT NULL," +
		"Sector   varchar(100) NOT NULL);")

	if err != nil {
		str += fmt.Sprintf("ERROR create CodesRight: %s", err)
	}
	str += "\n\n&#9940;БД удалены и созданы заново!"

	_, err = db.Exec("CREATE INDEX ON CodesUser(NickName text_pattern_ops);")
	if err != nil {
		str += fmt.Sprintf("ERROR create index: %s", err)
	}
	str += "\n\n&#9940;Индекс NickName в БД CodesUser создан!"

	return str
}
func (confDataBase *DataBase) DBSelectAllCodesRight() []DataBase {
	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		log.Printf(errConnectPattern, err)
	}
	defer db.Close()

	rows, err := db.Query("SELECT Number, Code, Danger, Sector FROM CodesRight")
	if err != nil {
		log.Printf("Unable to SELECT CodesRight: %v\n", err)
	}
	defer rows.Close()

	var data []DataBase
	for rows.Next() {
		d := DataBase{}
		err := rows.Scan(&d.Number, &d.Code, &d.Danger, &d.Sector)
		if err != nil {
			log.Println(err)
			continue
		}
		data = append(data, d)
	}

	return data
}
func (confDataBase *DataBase) DBSelectAllCodesUser() []DataBase {
	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		log.Printf(errConnectPattern, err)
	}
	defer db.Close()

	rows, err := db.Query("SELECT Number, Time, NickName, Code, Danger, Sector FROM CodesUser")
	if err != nil {
		log.Printf("Unable to SELECT CodesUser: %v\n", err)
	}
	defer rows.Close()

	var data []DataBase
	for rows.Next() {
		d := DataBase{}
		err := rows.Scan(&d.Number, &d.Time, &d.NickName, &d.Code, &d.Danger, &d.Sector)
		if err != nil {
			log.Println(err)
			continue
		}
		data = append(data, d)
	}

	return data
}

func (confDataBase *DataBase) DBResetUser() (str string) {
	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		return fmt.Sprintf(errConnectPattern, err)
	}
	defer db.Close()

	// delete table
	_, err = db.Exec("DROP TABLE IF EXISTS Users")
	if err != nil {
		str += fmt.Sprintf("ERROR delete Users: %s", err)
	}
	_, err = db.Exec("DROP TABLE IF EXISTS Teams")
	if err != nil {
		str += fmt.Sprintf("ERROR delete Teams: %s", err)
	}

	// create table
	_, err = db.Exec("CREATE TABLE " +
		"Teams(" +
		"ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
		"Time    varchar(40) NOT NULL," +
		"Team varchar(100) UNIQUE NOT NULL," +
		"Hash   varchar(100) NOT NULL," +
		"Owner   varchar(100) NOT NULL);")
	if err != nil {
		str += fmt.Sprintf("ERROR create Teams: %s", err)
	}

	_, err = db.Exec("CREATE TABLE " +
		"Users( " +
		"ID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
		"NickName varchar(100) NOT NULL," +
		"Time    varchar(40) NOT NULL," +
		"Team varchar(100) UNIQUE NOT NULL," +
		"Login    varchar(100) NOT NULL," +
		"Password   varchar(100) NOT NULL);")
	if err != nil {
		str += fmt.Sprintf("ERROR create Users: %s", err)
	}

	str += "\n\n&#9940;БД удалены и созданы заново!"

	return str
}
func (confDataBase *Teams) DBCreateTeam() string {

	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		log.Printf(errConnectPattern, err)
	}
	defer db.Close()

	_, err = db.Exec("INSERT INTO Teams (Time, Team,  Hash, Owner) VALUES ($1, $2, $3, $4)",
		confDataBase.Time, confDataBase.Team, confDataBase.Hash, confDataBase.Owner)
	if err != nil {
		log.Println(err)
		return err.Error()
	}
	return fmt.Sprintf("Команда %s создана, для вступления в неё введите: <code>/join %s %s </code>", confDataBase.Team, confDataBase.Team, confDataBase.Hash)
}
func (confDataBase *Users) DBSelectUsers() []Users {
	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		log.Printf(errConnectPattern, err)
	}
	defer db.Close()

	rows, err := db.Query("SELECT NickName, Team FROM Users")
	if err != nil {
		log.Printf("Unable to SELECT Users: %v\n", err)
	}
	defer rows.Close()

	var data []Users
	for rows.Next() {
		d := Users{}
		err := rows.Scan(&d.NickName, &d.Team)
		if err != nil {
			log.Println(err)
			continue
		}
		data = append(data, d)
	}

	return data
}
func (confDataBase *Teams) DBSelectTeam() []Teams {
	db, err := sql.Open(confDataBase.DriverNameDB, confDataBase.DBURL)
	if err != nil {
		log.Printf(errConnectPattern, err)
	}
	defer db.Close()

	rows, err := db.Query("SELECT ID, Time, Team, Hash, Owner FROM Teams")
	if err != nil {
		log.Printf("Unable to SELECT Teams: %v\n", err)
	}
	defer rows.Close()

	var data []Teams
	for rows.Next() {
		d := Teams{}
		err := rows.Scan(&d.ID, &d.Time, &d.Team, &d.Hash, &d.Owner)
		if err != nil {
			log.Println(err)
			continue
		}
		data = append(data, d)
	}

	return data
}
